### ISSUE TITLE
Python 2.7.5 error 

### ISSUE THREAD

**Issue by menkeyi** [vmware/nsxramlclient#24]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/nsxramlclient/client.py", line 54, in __init__
    self._nsxraml = NsxRaml(self._nsx_raml_file, nsxmanager)
  File "/usr/lib/python2.7/site-packages/nsxramlclient/client.py", line 309, in __init__
    self._nsxraml = pyraml.parser.load(raml_file)
  File "/usr/lib/python2.7/site-packages/pyraml/parser.py", line 154, in load
    return parse(c, relative_path)
  File "/usr/lib/python2.7/site-packages/pyraml/parser.py", line 184, in parse
    context = ParseContext(yaml.load(c), relative_path)
  File "/usr/lib64/python2.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 45, in get_single_data
    return self.construct_document(node)
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 54, in construct_document
    for dummy in generator:
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 404, in construct_yaml_map
    value = self.construct_mapping(node)
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 214, in construct_mapping
    return BaseConstructor.construct_mapping(self, node, deep=deep)
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 139, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 94, in construct_object
    data = constructor(self, node)
  File "/usr/lib64/python2.7/site-packages/yaml/constructor.py", line 420, in construct_undefined
    node.start_mark)
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!include'
  in "<unicode string>", line 5, column 13:
       content: !include documentation/introduct ...

I am running this problem now and I don’t know what it is.

**Comment by mstansberry** [comment]
issue appears to be `PyYAML==5.1.0` release on 2019-03-13
was able to resolve by pinning to `PyYAML==3.13`

**Comment by menkeyi** [comment]
Thank you, I am temporarily replacing the incompatible fields with re

**Comment by victor-zhao-ibm** [comment]
Can someone look into this issue or documented somewhere? I ran into this issue and it took me almost 4 hour to fix it...

**Comment by mzagozen** [comment]
I opened https://github.com/an2deg/pyraml-parser/pull/37 to fix it in the package where the error is coming from. Until it is accepted and a new version of `pyraml-parser` is released on PyPI, the workaround of pinning `PyYAML==3.13` must be used.

**Comment by mzagozen** [comment]
[pyraml-parser-0.1.8](https://pypi.org/project/pyraml-parser/0.1.8/) is now released with the fix. This issue can be closed.
